/**
 * AVENIR ÉTUDE — Base de données Carrières CI
 * Sources : Grey Search Africa Guide Salaires 2024-2025
 *           ivoiremploi.com · emploi.ci · jeune-afrique.com
 *           Direction Générale Emploi CI
 * ─────────────────────────────────────────────────────
 * 80 métiers · 14 secteurs · Salaires nets FCFA réels
 */
const CAREERS = [
  // ── TECHNOLOGIE & IA ───────────────────────────────────────
  {id:"m-001",nom:"Data Scientist",secteur:"Technologie & IA",icon:"📊",riasec:["I","C"],demande:"critical",croissance:34,salaire_min:400000,salaire_max:1200000,desc:"Analyse de données massives, machine learning, prise de décision basée sur les données. Forte demande dans les banques, télécoms et startups ivoiriennes.",competences:["Python","Machine Learning","SQL","Statistiques","TensorFlow"],formation:"ENSEA, INP-HB/ESI, Master Data Science",hot:true},
  {id:"m-002",nom:"Développeur Full Stack",secteur:"Technologie & IA",icon:"💻",riasec:["I","R"],demande:"critical",croissance:42,salaire_min:250000,salaire_max:900000,desc:"Développement d'applications web et mobiles front et back. Secteur en explosion avec la digitalisation massive des entreprises ivoiriennes.",competences:["React","Node.js","Python","Flutter","Bases de données"],formation:"ESATIC, INP-HB/ESI, IMAT",hot:true},
  {id:"m-003",nom:"Expert Cybersécurité",secteur:"Technologie & IA",icon:"🛡️",riasec:["I","R"],demande:"critical",croissance:51,salaire_min:400000,salaire_max:900000,desc:"Protection des systèmes d'information. Demande explosive avec la digitalisation bancaire et gouvernementale en CI.",competences:["SIEM","Pentest","ISO 27001","Réseaux","Forensics"],formation:"ESATIC — Master Cybersécurité",hot:true},
  {id:"m-004",nom:"Ingénieur DevOps / Cloud",secteur:"Technologie & IA",icon:"☁️",riasec:["I","R"],demande:"critical",croissance:45,salaire_min:350000,salaire_max:850000,desc:"Automatisation des déploiements, infrastructure cloud (AWS, Azure, GCP). Profil rare et très recherché en CI.",competences:["Docker","Kubernetes","CI/CD","AWS","Linux"],formation:"ESATIC, INP-HB/ESI",hot:true},
  {id:"m-005",nom:"Product Manager Tech",secteur:"Technologie & IA",icon:"🎯",riasec:["E","I"],demande:"high",croissance:48,salaire_min:350000,salaire_max:800000,desc:"Pilotage produit des applications et services digitaux. Profil très recherché dans les fintechs et startups ivoiriennes.",competences:["Agile/Scrum","UX","Data","Roadmap produit","OKR"],formation:"INP-HB, ENSEA + expérience terrain",hot:true},
  {id:"m-006",nom:"Architecte Logiciel",secteur:"Technologie & IA",icon:"🏛️",riasec:["I","R"],demande:"critical",croissance:38,salaire_min:400000,salaire_max:2450000,desc:"Conception de l'architecture technique des systèmes d'information. Parmi les profils les mieux payés en CI.",competences:["Architecture microservices","API","Cloud","Design patterns","Sécurité"],formation:"INP-HB/ESI, ESATIC + 3-5 ans expérience",hot:true},
  {id:"m-007",nom:"Business Analyst IT",secteur:"Technologie & IA",icon:"📋",riasec:["I","C"],demande:"high",croissance:35,salaire_min:200000,salaire_max:1850000,desc:"Interface entre la direction informatique et les directions opérationnelles. Traduction des besoins métiers en solutions techniques.",competences:["UML","BPMN","SQL","Rédaction fonctionnelle","Gestion projet"],formation:"ENSEA, INP-HB, HEC Abidjan",hot:false},
  {id:"m-008",nom:"Développeur Mobile",secteur:"Technologie & IA",icon:"📱",riasec:["I","R"],demande:"high",croissance:40,salaire_min:250000,salaire_max:700000,desc:"Création d'applications Android et iOS. Marché mobile en très forte croissance avec 20M+ d'utilisateurs mobile en CI.",competences:["Flutter","React Native","Swift","Kotlin","Firebase"],formation:"ESATIC, INP-HB/ESI",hot:false},
  {id:"m-009",nom:"Administrateur Systèmes & Réseaux",secteur:"Technologie & IA",icon:"🔧",riasec:["R","I"],demande:"high",croissance:22,salaire_min:200000,salaire_max:600000,desc:"Gestion et maintenance des infrastructures informatiques. Présent dans toutes les grandes entreprises ivoiriennes.",competences:["Linux","Windows Server","CISCO","Active Directory","Virtualisation"],formation:"ESATIC, INP-HB/ESI",hot:false},
  {id:"m-010",nom:"UX/UI Designer",secteur:"Technologie & IA",icon:"🎨",riasec:["A","I"],demande:"high",croissance:36,salaire_min:200000,salaire_max:650000,desc:"Conception des interfaces utilisateurs et de l'expérience digitale. Demande croissante avec le boom du digital en CI.",competences:["Figma","Adobe XD","Prototypage","Recherche utilisateur","HTML/CSS"],formation:"ESATIC, Écoles de design",hot:false},

  // ── BTP & INFRASTRUCTURE ───────────────────────────────────
  {id:"m-011",nom:"Ingénieur Génie Civil",secteur:"BTP & Infrastructure",icon:"🏗️",riasec:["R","I"],demande:"critical",croissance:28,salaire_min:350000,salaire_max:700000,desc:"Conception et supervision des grands chantiers. Demande portée par les projets métro, autoroutes et ponts en CI.",competences:["AutoCAD","BIM","Béton armé","Gestion chantier","ROBOT"],formation:"INP-HB/ESTP",hot:true},
  {id:"m-012",nom:"Architecte",secteur:"BTP & Infrastructure",icon:"📐",riasec:["A","I"],demande:"high",croissance:20,salaire_min:300000,salaire_max:650000,desc:"Conception des bâtiments et espaces urbains. Forte demande avec le développement immobilier à Abidjan.",competences:["AutoCAD","ArchiCAD","Urbanisme","Dessin technique","3D Max"],formation:"INP-HB/ESTP, École d'Architecture d'Abidjan",hot:false},
  {id:"m-013",nom:"Conducteur de Travaux",secteur:"BTP & Infrastructure",icon:"👷",riasec:["R","E"],demande:"high",croissance:25,salaire_min:250000,salaire_max:600000,desc:"Coordination des chantiers de construction. Profil très demandé par les entreprises BTP qui peinent à recruter des profils expérimentés.",competences:["Gestion chantier","Planning","Budget","Sécurité","Management"],formation:"INP-HB/ESTP, BTS Génie Civil",hot:false},
  {id:"m-014",nom:"Ingénieur Géotechnicien",secteur:"BTP & Infrastructure",icon:"⛏️",riasec:["R","I"],demande:"high",croissance:18,salaire_min:300000,salaire_max:650000,desc:"Étude des sols et fondations pour les grands projets d'infrastructure.",competences:["Géologie","Mécanique des sols","SIG","Forage","Calcul structures"],formation:"INP-HB/ESTP, ESMG",hot:false},
  {id:"m-015",nom:"Chiffreur BTP",secteur:"BTP & Infrastructure",icon:"🧮",riasec:["C","I"],demande:"high",croissance:20,salaire_min:250000,salaire_max:550000,desc:"Analyse des appels d'offres et établissement des estimations financières des projets BTP.",competences:["Métrés","Excel","Devis","Appels d'offres","Normes CI"],formation:"INP-HB/ESTP, BTS Génie Civil",hot:false},

  // ── FINANCE & COMPTABILITÉ ─────────────────────────────────
  {id:"m-016",nom:"Auditeur Financier",secteur:"Finance & Comptabilité",icon:"📈",riasec:["C","I"],demande:"high",croissance:22,salaire_min:350000,salaire_max:750000,desc:"Contrôle des comptes et certification des états financiers. Forte demande des multinationales installées à Abidjan.",competences:["SYSCOHADA","IFRS","Excel","Audit interne","Normes OHADA"],formation:"HEC Abidjan, CERAP, DSCG",hot:false},
  {id:"m-017",nom:"Contrôleur de Gestion",secteur:"Finance & Comptabilité",icon:"🧾",riasec:["C","I"],demande:"high",croissance:19,salaire_min:300000,salaire_max:650000,desc:"Pilotage financier et suivi budgétaire. Profil recherché dans toutes les grandes entreprises et groupes ivoiriens.",competences:["Budget","Reporting","Excel avancé","ERP SAP","Tableaux de bord"],formation:"HEC Abidjan, UFHB Éco-Gestion, ABS",hot:false},
  {id:"m-018",nom:"Analyste Financier",secteur:"Finance & Comptabilité",icon:"💹",riasec:["I","C"],demande:"high",croissance:24,salaire_min:300000,salaire_max:800000,desc:"Analyse des marchés financiers, évaluation d'entreprises et aide à la décision d'investissement.",competences:["Modélisation financière","Bloomberg","Excel","Valorisation","Due diligence"],formation:"ENSEA, HEC Abidjan, Licence Finance",hot:false},
  {id:"m-019",nom:"Responsable Comptable",secteur:"Finance & Comptabilité",icon:"📒",riasec:["C","I"],demande:"high",croissance:15,salaire_min:250000,salaire_max:600000,desc:"Supervision de la comptabilité générale et analytique de l'entreprise selon les normes SYSCOHADA.",competences:["SYSCOHADA","Paie","Déclarations fiscales","Logiciels comptables","Bilan"],formation:"HEC Abidjan, ABS, UFHB",hot:false},
  {id:"m-020",nom:"Acheteur / Supply Chain Manager",secteur:"Finance & Comptabilité",icon:"🛒",riasec:["C","E"],demande:"high",croissance:20,salaire_min:250000,salaire_max:1100000,desc:"Gestion des achats et de la chaîne d'approvisionnement. Rôle stratégique en contexte de hausse des prix des matières premières.",competences:["Négociation","ERP","Incoterms","Supply Chain","Sourcing Afrique"],formation:"HEC Abidjan, IMAT, BTS logistique",hot:false},
  {id:"m-021",nom:"Demand Planner",secteur:"Finance & Comptabilité",icon:"📦",riasec:["I","C"],demande:"high",croissance:18,salaire_min:450000,salaire_max:2600000,desc:"Régulation des flux de commandes, d'approvisionnement et de fabrication. Parmi les profils les plus recherchés et mieux payés.",competences:["Prévisions","Excel avancé","ERP SAP","Statistiques","Planification"],formation:"ENSEA, INP-HB Commerce",hot:true},
  {id:"m-022",nom:"Chargé de Recouvrement",secteur:"Finance & Comptabilité",icon:"💰",riasec:["E","C"],demande:"medium",croissance:12,salaire_min:150000,salaire_max:400000,desc:"Gestion du recouvrement des créances clients. Secteur bancaire et microfinance en forte croissance en CI.",competences:["Négociation","Droit civil","Excel","Communication","Suivi juridique"],formation:"UFHB Droit, BTS Comptabilité",hot:false},

  // ── SANTÉ & SCIENCES MÉDICALES ─────────────────────────────
  {id:"m-023",nom:"Médecin Généraliste",secteur:"Santé & Sciences médicales",icon:"⚕️",riasec:["S","I"],demande:"critical",croissance:15,salaire_min:400000,salaire_max:900000,desc:"Déficit chronique de médecins en CI. Débouchés garantis dans le public comme dans le privé.",competences:["Diagnostic clinique","Prescription","Urgences","Pédiatrie","Médecine tropicale"],formation:"UFHB — Faculté de Médecine",hot:true},
  {id:"m-024",nom:"Chirurgien",secteur:"Santé & Sciences médicales",icon:"🩺",riasec:["S","I"],demande:"critical",croissance:12,salaire_min:700000,salaire_max:2000000,desc:"Spécialiste chirurgical. Très peu nombreux en CI — les cliniques privées se battent pour les recruter.",competences:["Chirurgie générale","Bloc opératoire","Anatomie","Anesthésiologie","Urgences"],formation:"UFHB Médecine — spécialisation 5 ans",hot:true},
  {id:"m-025",nom:"Pharmacien",secteur:"Santé & Sciences médicales",icon:"💊",riasec:["I","R"],demande:"high",croissance:18,salaire_min:350000,salaire_max:800000,desc:"Dispensation et conseil pharmaceutique. Forte demande avec l'expansion des officines privées.",competences:["Pharmacologie","Galénique","Conseil patient","Gestion officine","Législation"],formation:"UFHB — Faculté de Pharmacie",hot:false},
  {id:"m-026",nom:"Infirmier Spécialisé",secteur:"Santé & Sciences médicales",icon:"🏥",riasec:["S","R"],demande:"critical",croissance:20,salaire_min:160000,salaire_max:450000,desc:"Soins infirmiers spécialisés (bloc, réanimation, pédiatrie). Déficit massif dans les hôpitaux publics et cliniques privées.",competences:["Soins infirmiers","Réanimation","Pédiatrie","Pharmacologie de base","Urgences"],formation:"INFAS, ISIS, Écoles de soins infirmiers",hot:false},
  {id:"m-027",nom:"Biologiste Médical",secteur:"Santé & Sciences médicales",icon:"🔬",riasec:["I","R"],demande:"high",croissance:16,salaire_min:400000,salaire_max:900000,desc:"Analyses biologiques et diagnostics en laboratoire. Secteur porté par le développement des cliniques privées.",competences:["Biochimie","Microbiologie","Hématologie","Immunologie","PCR"],formation:"UFHB Pharmacie/Médecine",hot:false},
  {id:"m-028",nom:"Médecin du Travail",secteur:"Santé & Sciences médicales",icon:"👨‍⚕️",riasec:["S","I"],demande:"high",croissance:14,salaire_min:500000,salaire_max:1200000,desc:"Prévention des risques professionnels. Toutes les entreprises de +50 salariés sont obligées d'en avoir un.",competences:["Médecine préventive","Toxicologie","Ergonomie","Réglementation du travail"],formation:"UFHB Médecine — spécialisation",hot:false},
  {id:"m-029",nom:"Sage-Femme",secteur:"Santé & Sciences médicales",icon:"👶",riasec:["S","R"],demande:"critical",croissance:18,salaire_min:150000,salaire_max:400000,desc:"Soins obstétricaux et gynécologiques. Manque chronique en zone rurale et péri-urbaine.",competences:["Obstétrique","Soins néonatals","Planification familiale","Urgences obstétricales"],formation:"INFAS, Écoles de sages-femmes",hot:false},

  // ── AGRONOMIE & AGROBUSINESS ───────────────────────────────
  {id:"m-030",nom:"Ingénieur Agronome",secteur:"Agronomie & Agrobusiness",icon:"🌱",riasec:["R","I"],demande:"high",croissance:18,salaire_min:280000,salaire_max:580000,desc:"La CI est le 1er producteur mondial de cacao. Les agronomes sont au cœur de la transformation agricole ivoirienne.",competences:["Agronomie tropicale","Certification qualité","Gestion exploitation","Cacao/café","SIG"],formation:"INP-HB/ESEA",hot:true},
  {id:"m-031",nom:"Expert Agro-industrie",secteur:"Agronomie & Agrobusiness",icon:"🏭",riasec:["R","I"],demande:"high",croissance:22,salaire_min:300000,salaire_max:700000,desc:"Transformation et valorisation des produits agricoles. Secteur stratégique dans la politique 'agrobusiness' du gouvernement CI.",competences:["Process industriel","HACCP","Qualité alimentaire","Gestion production","Supply chain agro"],formation:"INP-HB/ESEA, ESA",hot:false},
  {id:"m-032",nom:"Consultant Cacao & Café",secteur:"Agronomie & Agrobusiness",icon:"☕",riasec:["I","E"],demande:"high",croissance:15,salaire_min:350000,salaire_max:800000,desc:"Expertise sur la filière cacao-café ivoirienne, la 1ère au monde. Accompagnement des producteurs et acheteurs internationaux.",competences:["Filière cacao","Certification bio/équitable","Commerce international","Analyse qualité"],formation:"INP-HB/ESEA, Masters spécialisés",hot:false},
  {id:"m-033",nom:"Vétérinaire",secteur:"Agronomie & Agrobusiness",icon:"🐄",riasec:["R","I"],demande:"high",croissance:14,salaire_min:300000,salaire_max:700000,desc:"Santé animale et élevage. Secteur élevage en développement en CI — cliniques vétérinaires privées en expansion.",competences:["Médecine vétérinaire","Chirurgie animale","Santé publique vétérinaire","Élevage"],formation:"UFHB Sciences vétérinaires",hot:false},
  {id:"m-034",nom:"Ingénieur Halieutique",secteur:"Agronomie & Agrobusiness",icon:"🐟",riasec:["R","I"],demande:"medium",croissance:16,salaire_min:250000,salaire_max:550000,desc:"Gestion des ressources halieutiques et de l'aquaculture. La CI a un potentiel énorme en aquaculture encore sous-exploité.",competences:["Aquaculture","Ichtyologie","Pêche durable","Gestion des stocks"],formation:"INP-HB/ESEA",hot:false},

  // ── COMMERCE & MARKETING ──────────────────────────────────
  {id:"m-035",nom:"Responsable Marketing Digital",secteur:"Commerce & Marketing",icon:"📱",riasec:["E","A"],demande:"high",croissance:38,salaire_min:200000,salaire_max:500000,desc:"Gestion des canaux digitaux, e-commerce et campagnes en ligne. Boom du digital avec 14M+ d'utilisateurs internet en CI.",competences:["SEO/SEM","Social Media","Analytics","Content marketing","E-commerce"],formation:"HEC Abidjan, BEM Abidjan, ABS",hot:false},
  {id:"m-036",nom:"Ingénieur Commercial",secteur:"Commerce & Marketing",icon:"🤝",riasec:["E","S"],demande:"high",croissance:20,salaire_min:250000,salaire_max:1500000,desc:"Développement commercial B2B pour les entreprises tech, industrielles et de services. Primes de performance très élevées.",competences:["Négociation B2B","CRM","Prospection","Technique produit","Présentation"],formation:"HEC Abidjan, BEM Abidjan, INP-HB Commerce",hot:false},
  {id:"m-037",nom:"Business Developer Afrique",secteur:"Commerce & Marketing",icon:"🌍",riasec:["E","S"],demande:"high",croissance:30,salaire_min:300000,salaire_max:1000000,desc:"Développement de nouveaux marchés en Afrique subsaharienne. Abidjan hub régional — profil très recherché par les multinationales.",competences:["Développement commercial","Langues (anglais/français)","Négociation interculturelle","Réseau"],formation:"HEC Abidjan, BEM, AUCI",hot:true},
  {id:"m-038",nom:"Responsable Ressources Humaines",secteur:"Commerce & Marketing",icon:"👥",riasec:["S","E"],demande:"medium",croissance:15,salaire_min:200000,salaire_max:450000,desc:"Recrutement, formation et gestion des talents. Les grandes entreprises ivoiriennes et multinationales recrutent des DRH qualifiés.",competences:["GPEC","Droit du travail CI","Recrutement","Paie","Formation"],formation:"HEC Abidjan, IUA, ABS",hot:false},
  {id:"m-039",nom:"Community Manager",secteur:"Commerce & Marketing",icon:"📸",riasec:["A","E"],demande:"high",croissance:42,salaire_min:100000,salaire_max:350000,desc:"Animation des réseaux sociaux et création de contenu. Boom des médias sociaux en CI — toutes les entreprises recrutent.",competences:["Instagram","Facebook","TikTok","Canva","Copywriting"],formation:"Écoles de communication, autoformation",hot:false},
  {id:"m-040",nom:"Responsable E-commerce",secteur:"Commerce & Marketing",icon:"🛍️",riasec:["E","I"],demande:"high",croissance:45,salaire_min:200000,salaire_max:600000,desc:"Gestion des plateformes de vente en ligne. Boom du commerce électronique en CI avec l'essor du mobile money.",competences:["E-commerce","Logistique","SEO","Analytics","Mobile money"],formation:"HEC Abidjan, formations digitales",hot:true},

  // ── DROIT & INSTITUTIONS ──────────────────────────────────
  {id:"m-041",nom:"Juriste d'Affaires",secteur:"Droit & Institutions",icon:"⚖️",riasec:["I","E"],demande:"medium",croissance:14,salaire_min:300000,salaire_max:700000,desc:"Accompagnement juridique des entreprises : contrats, contentieux, compliance. Forte demande des multinationales.",competences:["Droit OHADA","Droit fiscal","Arbitrage","Rédaction juridique","Anglais juridique"],formation:"UFHB Droit, CERAP, IUA",hot:false},
  {id:"m-042",nom:"Avocat",secteur:"Droit & Institutions",icon:"👨‍⚖️",riasec:["E","I"],demande:"medium",croissance:12,salaire_min:300000,salaire_max:2000000,desc:"Conseil et représentation juridique. Les avocats d'affaires spécialisés en droit OHADA et droit des investissements sont très demandés.",competences:["Droit OHADA","Plaidoirie","Rédaction actes","Droit des affaires","Arbitrage CCJA"],formation:"UFHB Droit + École du Barreau",hot:false},
  {id:"m-043",nom:"Notaire",secteur:"Droit & Institutions",icon:"📜",riasec:["C","I"],demande:"medium",croissance:10,salaire_min:400000,salaire_max:1500000,desc:"Officier public authentifiant les actes juridiques. Profession réglementée très lucrative.",competences:["Droit notarial","Droit immobilier","Droit de la famille","Succession","Actes authentiques"],formation:"UFHB Droit + Institut Notarial",hot:false},
  {id:"m-044",nom:"Administrateur Civil",secteur:"Droit & Institutions",icon:"🏛️",riasec:["C","E"],demande:"high",croissance:8,salaire_min:250000,salaire_max:700000,desc:"Gestion administrative de l'État. Carrière stable avec progression garantie dans la fonction publique ivoirienne.",competences:["Droit public","Administration","Gestion budgétaire","Rédaction administrative","Procédures"],formation:"ENA Côte d'Ivoire, UFHB Droit",hot:false},
  {id:"m-045",nom:"Huissier de Justice",secteur:"Droit & Institutions",icon:"📋",riasec:["C","I"],demande:"medium",croissance:10,salaire_min:250000,salaire_max:600000,desc:"Officier ministériel chargé des significations et exécutions judiciaires.",competences:["Procédure civile","Droit OHADA","Signification","Saisie","Rédaction juridique"],formation:"UFHB Droit + Stage professionnel",hot:false},

  // ── LOGISTIQUE & TRANSPORT ────────────────────────────────
  {id:"m-046",nom:"Logisticien Portuaire",secteur:"Logistique & Transport",icon:"🚢",riasec:["C","E"],demande:"high",croissance:20,salaire_min:250000,salaire_max:550000,desc:"Gestion des flux au Port d'Abidjan, 1er port à conteneurs d'Afrique de l'Ouest. Secteur clé de l'économie ivoirienne.",competences:["Incoterms","Supply Chain","Douanes","ERP","Transit"],formation:"ISTC, INSUCA, École des Douanes CI",hot:false},
  {id:"m-047",nom:"Transitaire / Agent Douane",secteur:"Logistique & Transport",icon:"📦",riasec:["C","E"],demande:"high",croissance:18,salaire_min:200000,salaire_max:500000,desc:"Dédouanement et transit des marchandises. Le port d'Abidjan traite les imports/exports de toute la sous-région.",competences:["Réglementation douanière","SYDAM","Tarif douanier","Transit","Import-export"],formation:"École des Douanes CI, BTS Commerce International",hot:false},
  {id:"m-048",nom:"Responsable Chaîne Logistique",secteur:"Logistique & Transport",icon:"🔄",riasec:["C","E"],demande:"high",croissance:22,salaire_min:300000,salaire_max:700000,desc:"Optimisation de la supply chain des entreprises industrielles et de distribution.",competences:["ERP SAP","Lean","Gestion stocks","Transport","Planification"],formation:"HEC Abidjan, INP-HB Commerce, BTS Logistique",hot:false},
  {id:"m-049",nom:"Pilote de Ligne",secteur:"Logistique & Transport",icon:"✈️",riasec:["R","I"],demande:"high",croissance:15,salaire_min:800000,salaire_max:3000000,desc:"Commandant de bord pour les compagnies aériennes. Air Côte d'Ivoire et Ethiopian recrutent des pilotes ivoiriens.",competences:["ATPL","Navigation aérienne","Météorologie","CRM (Cockpit)","Anglais aviation"],formation:"Écoles de pilotage agréées ANAC CI",hot:false},
  {id:"m-050",nom:"Ingénieur Trafic / Planification Transport",secteur:"Logistique & Transport",icon:"🚇",riasec:["I","R"],demande:"high",croissance:25,salaire_min:300000,salaire_max:650000,desc:"Planification des réseaux de transport urbain. Très demandé avec les projets de métro d'Abidjan et extensions routières.",competences:["Modélisation trafic","SIG","Autocad","Études de mobilité","Urban Planning"],formation:"INP-HB/ESTP, Masters Urbanisme",hot:true},

  // ── TÉLÉCOMMUNICATIONS ────────────────────────────────────
  {id:"m-051",nom:"Ingénieur Télécoms",secteur:"Télécommunications",icon:"📡",riasec:["R","I"],demande:"high",croissance:24,salaire_min:300000,salaire_max:650000,desc:"Déploiement et maintenance des réseaux télécoms. Orange CI, MTN, Moov et Wave recrutent massivement.",competences:["4G/5G","Fibre optique","IP/MPLS","Antennes","Transmission"],formation:"ESATIC, INP-HB/ESI",hot:false},
  {id:"m-052",nom:"Ingénieur Systèmes Embarqués",secteur:"Télécommunications",icon:"🔌",riasec:["R","I"],demande:"high",croissance:28,salaire_min:300000,salaire_max:700000,desc:"Développement de systèmes électroniques embarqués. Demande dans l'industrie, les télécoms et l'IoT.",competences:["C/C++ embarqué","FPGA","Microcontrôleurs","IoT","RTOS"],formation:"INP-HB/ESI, ESATIC",hot:false},
  {id:"m-053",nom:"Expert Mobile Money / Fintech",secteur:"Télécommunications",icon:"📲",riasec:["I","E"],demande:"critical",croissance:55,salaire_min:350000,salaire_max:900000,desc:"Développement et gestion des services mobile money (Orange Money, MTN MoMo, Wave). La CI est leader africain du mobile money.",competences:["API paiement","Conformité financière","Développement mobile","Blockchain","Compliance"],formation:"ENSEA, ESATIC, INP-HB",hot:true},
  {id:"m-054",nom:"Ingénieur Qualité Réseau",secteur:"Télécommunications",icon:"📶",riasec:["R","I"],demande:"medium",croissance:18,salaire_min:280000,salaire_max:600000,desc:"Analyse et optimisation de la qualité des réseaux télécoms mobiles et fixes.",competences:["Drive test","Optimisation RF","Qualité de service","Outils télécom","Reporting"],formation:"ESATIC, INP-HB/ESI",hot:false},

  // ── ÉNERGIE & ENVIRONNEMENT ───────────────────────────────
  {id:"m-055",nom:"Ingénieur Énergie Solaire",secteur:"Énergie & Environnement",icon:"☀️",riasec:["R","I"],demande:"high",croissance:45,salaire_min:280000,salaire_max:600000,desc:"Installation et maintenance de systèmes photovoltaïques. Forte croissance avec les objectifs de transition énergétique de la CI.",competences:["Photovoltaïque","Électrotechnique","Onduleurs","Audit énergétique","Normes IEC"],formation:"INP-HB, Formations spécialisées",hot:true},
  {id:"m-056",nom:"Ingénieur Environnement",secteur:"Énergie & Environnement",icon:"🌿",riasec:["I","R"],demande:"high",croissance:28,salaire_min:280000,salaire_max:600000,desc:"Études d'impact environnemental et gestion des ressources naturelles. Obligatoire pour tout grand projet en CI.",competences:["EIE","SIG","Droit environnemental CI","Biodiversité","Pollution"],formation:"INP-HB/ESEA, UFHB Sciences Environnement",hot:false},
  {id:"m-057",nom:"Expert HSE",secteur:"Énergie & Environnement",icon:"⚠️",riasec:["R","C"],demande:"high",croissance:22,salaire_min:300000,salaire_max:1000000,desc:"Hygiène, Sécurité et Environnement dans les industries pétrolières, minières et BTP.",competences:["ISO 45001","Audit sécurité","Plan d'urgence","Formation sécurité","OHSAS"],formation:"INP-HB, Certifications HSE",hot:false},
  {id:"m-058",nom:"Ingénieur Pétrolier",secteur:"Énergie & Environnement",icon:"🛢️",riasec:["R","I"],demande:"high",croissance:20,salaire_min:500000,salaire_max:1500000,desc:"La CI possède des gisements pétroliers offshore. Total, CNR International et Petroci recrutent des ingénieurs pétroliers.",competences:["Géologie pétrolière","Forage","Simulation réservoir","Offshore","Pétrochimie"],formation:"INP-HB/ESMG, Formations spécialisées",hot:false},

  // ── ÉDUCATION & FORMATION ────────────────────────────────
  {id:"m-059",nom:"Enseignant Secondaire",secteur:"Éducation & Formation",icon:"📚",riasec:["S","A"],demande:"high",croissance:12,salaire_min:200000,salaire_max:400000,desc:"Recrutements massifs dans le secteur public via les concours MENETFP. Emploi stable et progression garantie.",competences:["Pédagogie","Discipline enseignée","Didactique","Évaluation","Gestion classe"],formation:"ENS, CAFOP, Université + concours enseignant",hot:false},
  {id:"m-060",nom:"Formateur en Entreprise",secteur:"Éducation & Formation",icon:"🎓",riasec:["S","E"],demande:"high",croissance:20,salaire_min:200000,salaire_max:500000,desc:"Conception et animation de formations professionnelles. Boom de la formation continue dans les grandes entreprises.",competences:["Ingénierie formation","Animation","E-learning","HRBP","Évaluation formation"],formation:"CAFOP, ENS, Master Ressources Humaines",hot:false},
  {id:"m-061",nom:"Directeur d'École",secteur:"Éducation & Formation",icon:"🏫",riasec:["E","S"],demande:"medium",croissance:10,salaire_min:250000,salaire_max:600000,desc:"Direction d'établissement scolaire public ou privé. Secteur privé scolaire en forte expansion à Abidjan.",competences:["Management","Pédagogie","Gestion financière","Réglementation scolaire","Communication"],formation:"CAFOP + expérience, ENS",hot:false},

  // ── MÉDIAS & COMMUNICATION ───────────────────────────────
  {id:"m-062",nom:"Journaliste Digital",secteur:"Médias & Communication",icon:"🎙️",riasec:["A","S"],demande:"medium",croissance:20,salaire_min:150000,salaire_max:350000,desc:"Production de contenus pour les médias numériques ivoiriens. Croissance des plateformes d'info en ligne.",competences:["Rédaction web","SEO","Reportage","Réseaux sociaux","Montage vidéo"],formation:"ISTC, UJLOG, IUA Communication",hot:false},
  {id:"m-063",nom:"Chargé de Communication",secteur:"Médias & Communication",icon:"📣",riasec:["A","E"],demande:"medium",croissance:18,salaire_min:150000,salaire_max:400000,desc:"Communication externe et interne des entreprises. Toutes les grandes structures recrutent des profils communication.",competences:["Relations presse","Communication institutionnelle","Rédaction","Événementiel","Réseaux sociaux"],formation:"ISTC, IUA Communication, HEC Abidjan",hot:false},
  {id:"m-064",nom:"Réalisateur / Vidéaste",secteur:"Médias & Communication",icon:"🎬",riasec:["A","E"],demande:"medium",croissance:25,salaire_min:150000,salaire_max:500000,desc:"Production audiovisuelle pour les entreprises, medias et plateformes digitales. Boom du contenu vidéo en CI.",competences:["Tournage","Montage","After Effects","YouTube","Storytelling"],formation:"ISTC, Écoles de cinéma, autoformation",hot:false},

  // ── TOURISME & HÔTELLERIE ────────────────────────────────
  {id:"m-065",nom:"Manager Hôtelier",secteur:"Tourisme & Hôtellerie",icon:"🏨",riasec:["E","S"],demande:"medium",croissance:16,salaire_min:250000,salaire_max:600000,desc:"Direction d'établissements hôteliers. Abidjan accueille des chaînes internationales (Sofitel, Pullman, Marriott) qui recrutent.",competences:["Management hôtelier","Revenue management","F&B","Relations clients","Yield management"],formation:"UMEF, IUA, Écoles hôtelières privées",hot:false},
  {id:"m-066",nom:"Guide Touristique",secteur:"Tourisme & Hôtellerie",icon:"🗺️",riasec:["S","A"],demande:"medium",croissance:20,salaire_min:100000,salaire_max:300000,desc:"Accompagnement de touristes nationaux et internationaux. CI : programme 'Sublime Côte d'Ivoire' du gouvernement.",competences:["Langues (anglais, espagnol)","Histoire CI","Patrimoine culturel","Communication","Organisation"],formation:"ISTC, Écoles de tourisme",hot:false},
  {id:"m-067",nom:"Chef Cuisinier",secteur:"Tourisme & Hôtellerie",icon:"👨‍🍳",riasec:["R","A"],demande:"medium",croissance:18,salaire_min:150000,salaire_max:500000,desc:"Art culinaire dans les hôtels et restaurants. Boom de la restauration haut de gamme à Abidjan.",competences:["Cuisine française","Cuisine africaine","Gestion stocks","HACCP","Management cuisine"],formation:"Lycées hôteliers, Écoles de cuisine",hot:false},

  // ── MINES & RESSOURCES ────────────────────────────────────
  {id:"m-068",nom:"Géologue Minier",secteur:"Mines & Ressources",icon:"⛏️",riasec:["R","I"],demande:"high",croissance:22,salaire_min:400000,salaire_max:900000,desc:"Exploration et exploitation des ressources minières. La CI possède d'importantes réserves d'or, manganèse et pétrole.",competences:["Géologie structurale","SIG","Forage","Géochimie","Modélisation 3D"],formation:"INP-HB/ESMG",hot:false},
  {id:"m-069",nom:"Ingénieur Mines",secteur:"Mines & Ressources",icon:"🔩",riasec:["R","I"],demande:"high",croissance:20,salaire_min:450000,salaire_max:1000000,desc:"Gestion et optimisation de l'exploitation minière. Mines d'or (Tongon, Bonikro) et manganèse en plein développement.",competences:["Mine à ciel ouvert","Explosifs","Sécurité minière","Géostatistiques","ERP mine"],formation:"INP-HB/ESMG",hot:false},
  {id:"m-070",nom:"Hydrogéologue",secteur:"Mines & Ressources",icon:"💧",riasec:["R","I"],demande:"medium",croissance:18,salaire_min:300000,salaire_max:650000,desc:"Gestion des ressources en eau souterraine. Problématique majeure dans le contexte d'urbanisation rapide de la CI.",competences:["Hydrogéologie","Forages","SIG","Qualité eau","Modélisation"],formation:"INP-HB/ESMG, UFHB Sciences de la Terre",hot:false},

  // ── SECTEURS ÉMERGENTS ────────────────────────────────────
  {id:"m-071",nom:"Statisticien Économiste",secteur:"Finance & Comptabilité",icon:"📊",riasec:["I","C"],demande:"high",croissance:25,salaire_min:350000,salaire_max:750000,desc:"Analyse économique et modélisation pour les banques, ONG et ministères. Diplôme ENSEA reconnu dans toute l'Afrique.",competences:["SAS","R","Économétrie","Modélisation","SPSS"],formation:"ENSEA Abidjan",hot:true},
  {id:"m-072",nom:"Actuaire",secteur:"Finance & Comptabilité",icon:"🎲",riasec:["I","C"],demande:"high",croissance:30,salaire_min:500000,salaire_max:1500000,desc:"Évaluation des risques financiers pour les assurances et banques. Profil très rare et extrêmement recherché en CI.",competences:["Mathématiques actuarielles","SAS","R","Normes Solvabilité 2","Statistiques"],formation:"ENSEA Abidjan — Master Actuariat",hot:true},
  {id:"m-073",nom:"Blockchain Developer",secteur:"Technologie & IA",icon:"🔗",riasec:["I","R"],demande:"high",croissance:60,salaire_min:400000,salaire_max:1200000,desc:"Développement de solutions basées sur la blockchain. Secteur naissant en CI mais en croissance explosive.",competences:["Solidity","Ethereum","Web3","DeFi","Smart contracts"],formation:"Autoformation + certifications internationales",hot:true},
  {id:"m-074",nom:"Ingénieur Intelligence Artificielle",secteur:"Technologie & IA",icon:"🤖",riasec:["I","R"],demande:"critical",croissance:65,salaire_min:500000,salaire_max:1500000,desc:"Développement de modèles d'IA et de machine learning. Le métier de l'avenir, déjà recherché par les banques et télécoms CI.",competences:["Deep Learning","NLP","TensorFlow","PyTorch","Computer Vision"],formation:"ENSEA, INP-HB/ESI + Masters spécialisés",hot:true},
  {id:"m-075",nom:"Entrepreneur Tech",secteur:"Technologie & IA",icon:"🚀",riasec:["E","I"],demande:"high",croissance:55,salaire_min:0,salaire_max:0,desc:"Création d'entreprises innovantes. Abidjan est la plus grande scène startup d'Afrique de l'Ouest francophone.",competences:["Business Model","Levée de fonds","Product","Leadership","Résilience"],formation:"HEC Abidjan, BEM, incubateurs CTIC, Orange Fab",hot:true},
  {id:"m-076",nom:"Expert RSE / Développement Durable",secteur:"Énergie & Environnement",icon:"♻️",riasec:["I","S"],demande:"high",croissance:32,salaire_min:280000,salaire_max:650000,desc:"Responsabilité Sociale et Environnementale des entreprises. Obligation croissante pour les grandes entreprises opérant en CI.",competences:["Reporting ESG","ISO 26000","Parties prenantes","Communication RSE","Audit"],formation:"INP-HB, Masters Développement Durable",hot:false},
  {id:"m-077",nom:"Ingénieur Qualité",secteur:"Commerce & Marketing",icon:"✅",riasec:["C","R"],demande:"high",croissance:18,salaire_min:250000,salaire_max:600000,desc:"Contrôle et amélioration de la qualité des produits et processus. Secteur agro-alimentaire et industriel très demandeur.",competences:["ISO 9001","HACCP","Six Sigma","Audit qualité","SPC"],formation:"INP-HB, Certifications ISO",hot:false},
  {id:"m-078",nom:"Expert Sécurité Incendie",secteur:"BTP & Infrastructure",icon:"🧯",riasec:["R","C"],demande:"medium",croissance:20,salaire_min:200000,salaire_max:500000,desc:"Prévention et lutte contre les incendies dans les bâtiments et industries. Réglementation CI de plus en plus stricte.",competences:["Normes incendie","Sprinklers","Plans évacuation","Formation sécurité"],formation:"Formations spécialisées, INP-HB",hot:false},
  {id:"m-079",nom:"Chercheur Universitaire",secteur:"Éducation & Formation",icon:"🔭",riasec:["I","A"],demande:"medium",croissance:15,salaire_min:400000,salaire_max:1200000,desc:"Recherche fondamentale et appliquée. Les universités CI et les laboratoires de recherche recrutent des docteurs.",competences:["Méthodes de recherche","Publication scientifique","Enseignement","Statistiques","Anglais académique"],formation:"UFHB, INP-HB — Doctorat requis",hot:false},
  {id:"m-080",nom:"Diplomate / Fonctionnaire International",secteur:"Droit & Institutions",icon:"🌐",riasec:["E","S"],demande:"medium",croissance:10,salaire_min:500000,salaire_max:2000000,desc:"Représentation de la CI à l'international ou dans les organisations internationales (ONU, UA, CEDEAO).",competences:["Droit international","Langues (anglais, espagnol)","Négociation","Protocole","Relations internationales"],formation:"ENA CI, Sciences Po, Universités + concours diplomatique",hot:false},
];
