/**
 * ============================================================
 *  AVENIR ÉTUDE — BASE DE DONNÉES DES ÉCOLES
 *  Fichier : ecoles-data.js
 * ============================================================
 *
 *  ✅ COMMENT AJOUTER UNE ÉCOLE :
 *
 *  1. Copie un bloc { ... } existant
 *  2. Colle-le AVANT le dernier crochet ]
 *  3. Assure-toi qu'il y a une virgule après le } précédent
 *  4. Remplis les informations
 *  5. Sauvegarde le fichier — la page se met à jour automatiquement
 *
 *  ⚠️  RÈGLES IMPORTANTES :
 *  - Textes entre guillemets "comme ceci"
 *  - Listes entre crochets ["item1", "item2"]
 *  - Nombres sans guillemets : 85000  (pas "85000")
 *  - Pour les champs inconnus, mets null (sans guillemets)
 *
 * ============================================================
 */

const ECOLES_DATA = [

  // ─── 1 ───────────────────────────────────────────────────
  {
    id: "CI-001",
    nom: "Institut National Polytechnique Félix Houphouët-Boigny",
    acronyme: "INP-HB",
    type: "Grande École Publique",       // Grande École Publique | Université Publique | Grande École Privée | Université Privée
    statut: "public",                    // public | prive
    ville: "Yamoussoukro",
    commune: "Yamoussoukro",
    pays: "Côte d'Ivoire",
    site_web: "inphb.edu.ci",
    description: "La meilleure école technique de Côte d'Ivoire, regroupant 11 grandes écoles sur un campus de 4 sites. Partenariat avec le CNAM France.",
    domaines: ["Ingénierie", "Agronomie", "Commerce", "BTP", "Mines"],
    filieres: ["Génie Civil", "Génie Informatique", "Agronomie", "Commerce & Gestion", "Mines & Géologie", "Génie Mécanique"],
    niveaux: ["BTS", "Licence Pro", "Master", "Ingénieur"],
    series_bac: ["C", "D", "E", "F2"],
    admission: "Concours national",
    frais_inscription: "Non communiqué",
    frais_scolarite: "Pris en charge par l'État",
    effectif: 3000,
    taux_insertion: 100,                  // en %
    taux_reussite: 92,                    // en %
    note_ae: 4.8,                         // note sur 5
    classement_national: 1,
    tags_riasec: ["R", "I", "C"],        // types RIASEC compatibles
    label: "Top Classement",             // label spécial (ou null)
    bourse_dispo: true,
    enseignement_anglais: false
  },

  // ─── 2 ───────────────────────────────────────────────────
  {
    id: "CI-002",
    nom: "École Nationale Supérieure de Statistique et d'Économie Appliquée",
    acronyme: "ENSEA",
    type: "Grande École Publique",
    statut: "public",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: "ensea.ed.ci",
    description: "Centre d'Excellence Banque Mondiale depuis 2015. Vocation régionale avec des étudiants de 20+ pays africains.",
    domaines: ["Statistique", "Économie", "Data Science", "Actuariat"],
    filieres: ["Ingénieur Statisticien Économiste", "Analyste Statisticien", "Master Data Science", "Master Actuariat"],
    niveaux: ["Licence", "Master", "Doctorat"],
    series_bac: ["C", "D"],
    admission: "Concours (Janvier–Avril)",
    frais_inscription: "60000",
    frais_scolarite: "1600000",
    effectif: 400,
    taux_insertion: 95,
    taux_reussite: 90,
    note_ae: 4.7,
    classement_national: 2,
    tags_riasec: ["I", "C"],
    label: "Centre d'Excellence",
    bourse_dispo: true,
    enseignement_anglais: false
  },

  // ─── 3 ───────────────────────────────────────────────────
  {
    id: "CI-003",
    nom: "École Supérieure Africaine des Technologies de l'Information et de la Communication",
    acronyme: "ESATIC",
    type: "Grande École Publique",
    statut: "public",
    ville: "Abidjan",
    commune: "Treichville",
    pays: "Côte d'Ivoire",
    site_web: "esatic.ci",
    description: "Scolarité quasi-gratuite financée par l'État. Logement disponible à 3 500 FCFA/mois. 100 places par an en Licence.",
    domaines: ["Informatique", "Télécommunications", "Cybersécurité", "Réseaux"],
    filieres: ["Licence SRIT", "Licence RTEL", "Licence SIGL", "Master SITW", "Master MBDS"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "C", "D", "E", "F2"],
    admission: "Concours",
    frais_inscription: "10000",
    frais_scolarite: "Pris en charge par l'État",
    effectif: 600,
    taux_insertion: 90,
    taux_reussite: 85,
    note_ae: 4.5,
    classement_national: 3,
    tags_riasec: ["R", "I"],
    label: "Gratuit",
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 4 ───────────────────────────────────────────────────
  {
    id: "CI-004",
    nom: "Université Félix Houphouët-Boigny",
    acronyme: "UFHB",
    type: "Université Publique",
    statut: "public",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: "univ-fhb.edu.ci",
    description: "La plus grande université de Côte d'Ivoire avec 13 UFR et plus de 60 000 étudiants sur un campus de 200 hectares.",
    domaines: ["Droit", "Médecine", "Sciences", "Économie", "Informatique", "Lettres", "Pharmacie"],
    filieres: ["Biosciences", "Droit & Sciences Politiques", "Économie & Gestion", "Mathématiques & Informatique", "Médecine", "Pharmacie"],
    niveaux: ["Licence", "Master", "Doctorat", "DUT"],
    series_bac: ["A", "B", "C", "D", "E"],
    admission: "Affectation MESRS / Inscription directe",
    frais_inscription: "Non communiqué",
    frais_scolarite: "30000",
    effectif: 60000,
    taux_insertion: 60,
    taux_reussite: 55,
    note_ae: 3.8,
    classement_national: 4,
    tags_riasec: ["I", "S", "E"],
    label: null,
    bourse_dispo: true,
    enseignement_anglais: false
  },

  // ─── 5 ───────────────────────────────────────────────────
  {
    id: "CI-005",
    nom: "Université Nangui Abrogoua",
    acronyme: "UNA",
    type: "Université Publique",
    statut: "public",
    ville: "Abidjan",
    commune: "Abobo",
    pays: "Côte d'Ivoire",
    site_web: "una.edu.ci",
    description: "Université spécialisée en sciences et technologies. Forte en informatique, mathématiques et sciences de la nature.",
    domaines: ["Sciences", "Technologies", "Informatique", "Environnement"],
    filieres: ["Informatique", "Mathématiques", "Sciences de la Nature", "Chimie", "Biologie"],
    niveaux: ["Licence", "Master", "Doctorat"],
    series_bac: ["C", "D", "E"],
    admission: "Affectation MESRS",
    frais_inscription: "Non communiqué",
    frais_scolarite: "30000",
    effectif: 15000,
    taux_insertion: 55,
    taux_reussite: 50,
    note_ae: 3.5,
    classement_national: 5,
    tags_riasec: ["R", "I"],
    label: null,
    bourse_dispo: true,
    enseignement_anglais: false
  },

  // ─── 6 ───────────────────────────────────────────────────
  {
    id: "CI-006",
    nom: "Université Alassane Ouattara",
    acronyme: "UAO",
    type: "Université Publique",
    statut: "public",
    ville: "Bouaké",
    commune: "Bouaké",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Deuxième université publique de Côte d'Ivoire. Forte en économie, sciences sociales et langues étrangères.",
    domaines: ["Économie", "Sciences Sociales", "Lettres", "Langues"],
    filieres: ["Économie", "Sociologie", "Géographie", "Langues étrangères", "Droit"],
    niveaux: ["Licence", "Master", "Doctorat"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Affectation MESRS",
    frais_inscription: "Non communiqué",
    frais_scolarite: "30000",
    effectif: 20000,
    taux_insertion: 50,
    taux_reussite: 48,
    note_ae: 3.3,
    classement_national: 6,
    tags_riasec: ["S", "E", "A"],
    label: null,
    bourse_dispo: true,
    enseignement_anglais: false
  },

  // ─── 7 ───────────────────────────────────────────────────
  {
    id: "CI-007",
    nom: "Hautes Études Commerciales d'Abidjan",
    acronyme: "HEC Abidjan",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: "hecabidjan.ci",
    description: "Créée en 2001. Partenariats Royaume-Uni et France. Accréditation FEDE. Programmes en français et anglais.",
    domaines: ["Commerce", "Finance", "Management", "Marketing", "RH"],
    filieres: ["Licence Management", "Licence Finance", "Licence Marketing", "Master MBA", "Bachelor (Anglais)", "DBA"],
    niveaux: ["Licence", "Master", "MBA", "DBA"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier + entretien",
    frais_inscription: "175000",
    frais_scolarite: "900000",
    effectif: 2500,
    taux_insertion: 80,
    taux_reussite: 78,
    note_ae: 4.1,
    classement_national: 7,
    tags_riasec: ["E", "C", "S"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: true
  },

  // ─── 8 ───────────────────────────────────────────────────
  {
    id: "CI-008",
    nom: "Institut Universitaire d'Abidjan",
    acronyme: "IUA",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: "iuaci.org",
    description: "Institution catholique reconnue. Cadre international. Forte culture humaniste et remise de diplômes annuelle prestigieuse.",
    domaines: ["Droit", "Économie", "Management", "Sciences Politiques", "Communication"],
    filieres: ["Droit des Affaires", "Économie", "Management", "Sciences Politiques", "Communication"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "Non communiqué",
    frais_scolarite: "750000",
    effectif: 3000,
    taux_insertion: 72,
    taux_reussite: 70,
    note_ae: 3.9,
    classement_national: 8,
    tags_riasec: ["E", "S", "I"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 9 ───────────────────────────────────────────────────
  {
    id: "CI-009",
    nom: "American University of Côte d'Ivoire",
    acronyme: "AUCI",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: "auci.edu.ci",
    description: "Système américain. Cours principalement en anglais. Diplômes reconnus à l'international.",
    domaines: ["Business", "Ingénierie", "Informatique", "Sciences Sociales"],
    filieres: ["Business Administration", "Computer Science", "Engineering", "Social Sciences"],
    niveaux: ["Bachelor", "Master", "MBA"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier + entretien",
    frais_inscription: "200000",
    frais_scolarite: "2000000",
    effectif: 1200,
    taux_insertion: 78,
    taux_reussite: 75,
    note_ae: 3.8,
    classement_national: 9,
    tags_riasec: ["E", "I"],
    label: "Anglophone",
    bourse_dispo: false,
    enseignement_anglais: true
  },

  // ─── 10 ──────────────────────────────────────────────────
  {
    id: "CI-010",
    nom: "Centre de Recherche et d'Action pour la Paix – Université Jésuite",
    acronyme: "CERAP / UJ",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: "cerap-inades.org",
    description: "Institution jésuite de référence. Très sélective. Forte culture humaniste, philosophique et sociale.",
    domaines: ["Philosophie", "Théologie", "Sciences Sociales", "Management", "Droit"],
    filieres: ["Philosophie", "Théologie", "Droit", "Management", "Sciences Sociales"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier + entretien de sélection",
    frais_inscription: "Non communiqué",
    frais_scolarite: "800000",
    effectif: 1000,
    taux_insertion: 70,
    taux_reussite: 72,
    note_ae: 3.7,
    classement_national: 10,
    tags_riasec: ["S", "I", "A"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 11 ──────────────────────────────────────────────────
  {
    id: "CI-011",
    nom: "Swiss UMEF University of Côte d'Ivoire",
    acronyme: "UMEF",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Partenariat suisse. Diplôme reconnu à l'international. Spécialisé en management, finance et hôtellerie.",
    domaines: ["Management", "Finance", "Hôtellerie", "Marketing", "Tourisme"],
    filieres: ["Management", "Finance d'Entreprise", "Hôtellerie-Restauration", "Marketing", "Tourisme"],
    niveaux: ["Licence", "Master", "MBA"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "115000",
    frais_scolarite: "1500000",
    effectif: 800,
    taux_insertion: 75,
    taux_reussite: 73,
    note_ae: 3.8,
    classement_national: 11,
    tags_riasec: ["E", "C"],
    label: "Partenariat Suisse",
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 12 ──────────────────────────────────────────────────
  {
    id: "CI-012",
    nom: "Université de l'Atlantique",
    acronyme: "UA",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Présence à Abidjan et Bouaké. Frais accessibles. Filières classiques en économie, droit et informatique.",
    domaines: ["Économie", "Gestion", "Droit", "Informatique"],
    filieres: ["Économie", "Gestion", "Droit", "Informatique", "Marketing"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "Non communiqué",
    frais_scolarite: "600000",
    effectif: 3500,
    taux_insertion: 65,
    taux_reussite: 62,
    note_ae: 3.4,
    classement_national: 12,
    tags_riasec: ["E", "C", "I"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 13 ──────────────────────────────────────────────────
  {
    id: "CI-013",
    nom: "Institut Supérieur d'Ingénierie et de Santé",
    acronyme: "ISIS",
    type: "Grande École Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Double implantation : Cocody et Yamoussoukro. Spécialisé en ingénierie et santé.",
    domaines: ["Ingénierie", "Santé", "Informatique"],
    filieres: ["Génie Informatique", "Génie Électrique", "Soins Infirmiers", "Pharmacie"],
    niveaux: ["Licence", "Master", "Ingénieur"],
    series_bac: ["C", "D", "E", "F2"],
    admission: "Dossier + test de niveau",
    frais_inscription: "85000",
    frais_scolarite: "1000000",
    effectif: 1500,
    taux_insertion: 70,
    taux_reussite: 68,
    note_ae: 3.6,
    classement_national: 13,
    tags_riasec: ["R", "I"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 14 ──────────────────────────────────────────────────
  {
    id: "CI-014",
    nom: "Abidjan Business School",
    acronyme: "ABS",
    type: "Grande École Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "École de commerce reconnue. Filières business, finance et RH. Insertion correcte dans le secteur privé ivoirien.",
    domaines: ["Business", "Finance", "Marketing", "Ressources Humaines"],
    filieres: ["Management", "Finance d'Entreprise", "Marketing", "RH", "Audit-Comptabilité"],
    niveaux: ["Licence", "Master", "BTS"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "85000",
    frais_scolarite: "900000",
    effectif: 2000,
    taux_insertion: 68,
    taux_reussite: 65,
    note_ae: 3.5,
    classement_national: 14,
    tags_riasec: ["E", "C"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 15 ──────────────────────────────────────────────────
  {
    id: "CI-015",
    nom: "Bordeaux École de Management Abidjan",
    acronyme: "BEM Abidjan",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Antenne de BEM Bordeaux France. Diplôme français reconnu. Formation management, marketing et commerce international.",
    domaines: ["Management", "Marketing", "Finance", "Commerce International"],
    filieres: ["Management", "Marketing", "Finance", "Commerce International", "Entrepreneuriat"],
    niveaux: ["Bachelor", "Master", "MBA"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier + entretien",
    frais_inscription: "Non communiqué",
    frais_scolarite: "2000000",
    effectif: 600,
    taux_insertion: 76,
    taux_reussite: 74,
    note_ae: 3.9,
    classement_national: 15,
    tags_riasec: ["E", "S"],
    label: "Diplôme Français",
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 16 ──────────────────────────────────────────────────
  {
    id: "CI-016",
    nom: "Facultés Universitaires Privées d'Abidjan",
    acronyme: "FUPA",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Université privée polyvalente. Filières droit, économie, gestion et santé. Présence significative à Abidjan.",
    domaines: ["Droit", "Économie", "Gestion", "Santé"],
    filieres: ["Droit", "Économie", "Gestion", "Sciences de la Santé"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "165000",
    frais_scolarite: "1000000",
    effectif: 2500,
    taux_insertion: 65,
    taux_reussite: 63,
    note_ae: 3.5,
    classement_national: 16,
    tags_riasec: ["S", "E", "I"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 17 ──────────────────────────────────────────────────
  {
    id: "CI-017",
    nom: "Rusta Université",
    acronyme: "RUSTA",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Présence Abidjan et Bouaké. Filières classiques accessibles. Frais raisonnables pour les filières professionnalisantes.",
    domaines: ["Droit", "Économie", "Management", "Informatique"],
    filieres: ["Droit", "Économie", "Gestion", "Informatique"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "Non communiqué",
    frais_scolarite: "550000",
    effectif: 2000,
    taux_insertion: 62,
    taux_reussite: 60,
    note_ae: 3.3,
    classement_national: 17,
    tags_riasec: ["E", "C"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 18 ──────────────────────────────────────────────────
  {
    id: "CI-018",
    nom: "Institut de Management et des Technologies",
    acronyme: "IMAT",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Formation en management et technologies. Profils polyvalents orientés vers les entreprises et la tech.",
    domaines: ["Management", "Technologies", "Informatique", "Finance"],
    filieres: ["Management", "Informatique", "Finance", "Entrepreneuriat"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "100000",
    frais_scolarite: "800000",
    effectif: 1200,
    taux_insertion: 65,
    taux_reussite: 63,
    note_ae: 3.4,
    classement_national: 18,
    tags_riasec: ["E", "I"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 19 ──────────────────────────────────────────────────
  {
    id: "CI-019",
    nom: "Université des Lagunes",
    acronyme: "UDL",
    type: "Université Privée",
    statut: "prive",
    ville: "Abidjan",
    commune: "Cocody",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Université privée polyvalente avec une bonne réputation en droit et sciences économiques.",
    domaines: ["Droit", "Sciences Économiques", "Gestion", "Lettres"],
    filieres: ["Droit", "Économie", "Gestion", "Lettres", "Sciences Politiques"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "190000",
    frais_scolarite: "900000",
    effectif: 1800,
    taux_insertion: 64,
    taux_reussite: 62,
    note_ae: 3.5,
    classement_national: 19,
    tags_riasec: ["S", "E"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  },

  // ─── 20 ──────────────────────────────────────────────────
  {
    id: "CI-020",
    nom: "Seeka University",
    acronyme: "Seeka U",
    type: "Université Privée",
    statut: "prive",
    ville: "Yamoussoukro",
    commune: "Yamoussoukro",
    pays: "Côte d'Ivoire",
    site_web: null,
    description: "Université privée basée à Yamoussoukro. Filières sciences, technologies, management et santé.",
    domaines: ["Sciences", "Technologies", "Management", "Santé"],
    filieres: ["Informatique", "Génie", "Management", "Sciences de la Santé"],
    niveaux: ["Licence", "Master"],
    series_bac: ["A", "B", "C", "D"],
    admission: "Dossier",
    frais_inscription: "100000",
    frais_scolarite: "700000",
    effectif: 800,
    taux_insertion: 60,
    taux_reussite: 58,
    note_ae: 3.2,
    classement_national: 20,
    tags_riasec: ["I", "R"],
    label: null,
    bourse_dispo: false,
    enseignement_anglais: false
  }

  // ─── ✅ AJOUTE TES NOUVELLES ÉCOLES ICI ──────────────────
  // Copie un bloc { ... } ci-dessus, colle-le ici,
  // ajoute une virgule après le bloc précédent,
  // et remplis les informations.

];
